"""add owner_id to notes table.

Revision ID: 07a9b4a9f497
Revises: 6f95aecb0be8
Create Date: 2024-01-04 14:17:02.644476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a9b4a9f497'
down_revision: Union[str, None] = '6f95aecb0be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'owner_id')
    # ### end Alembic commands ###
