"""added indexes and timestamps

Revision ID: b83a37a8b3b5
Revises: e9a03a1dad4d
Create Date: 2024-01-04 23:35:02.574347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83a37a8b3b5'
down_revision: Union[str, None] = 'e9a03a1dad4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('notes', 'detail',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    op.add_column('shared_notes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_shared_notes_created_at'), 'shared_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_shared_notes_permission'), 'shared_notes', ['permission'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_notes_permission'), table_name='shared_notes')
    op.drop_index(op.f('ix_shared_notes_created_at'), table_name='shared_notes')
    op.drop_column('shared_notes', 'created_at')
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.alter_column('notes', 'detail',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('notes', 'created_at')
    # ### end Alembic commands ###
