"""remove category model

Revision ID: e9a03a1dad4d
Revises: f24b66a347b1
Create Date: 2024-01-04 22:16:06.201633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9a03a1dad4d"
down_revision: Union[str, None] = "f24b66a347b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("notes_category_id_fkey", "notes", type_="foreignkey")
    op.drop_table("categories")
    op.drop_column("notes", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes",
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "notes_category_id_fkey",
        "notes",
        "categories",
        ["category_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="categories_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="categories_pkey"),
        sa.UniqueConstraint("name", "user_id", name="unique_category_per_user"),
    )
    # ### end Alembic commands ###
